import xlsxwriter
import os, fnmatch
import xlrd
from openpyxl.workbook import Workbook


def xlsxwrite(header, data):
    header = header
    new_data = data

    wb = Workbook()
    dest_filename = 'Приказы.xlsx'
    ws1 = wb.active
    ws1.title = 'Приказы'
    ws1.append(header)

    for row in new_data:
        ws1.append(row)

    wb.save(filename = dest_filename)


def readxlsx(pathname):

    path = pathname

    workbook = xlrd.open_workbook(path)
    worksheet = workbook.sheet_by_index(0)
    # Change this depending on how many header rows are present
    # Set to 0 if you want to include the header data.
    offset = 1

    rows = []
    for i, row in enumerate(range(worksheet.nrows)):
        if i <= offset-1:  # (Optionally) skip headers
            continue
        r = []
        for j, col in enumerate(range(worksheet.ncols)):
            r.append(worksheet.cell_value(i, j))
        rows.append(r)

    print('Got ',len(rows) - offset,' rows')
    print(rows[0])  # Print first data row sample
    print(rows[offset])
    return rows


def find_files(directory, pattern):
    for root, dirs, files in os.walk(directory):
        for basename in files:
            if fnmatch.fnmatch(basename, pattern):
                filename = os.path.join(root, basename)
                yield filename


rows = []

for filename in find_files('C:\\Users\\HYPER\\PycharmProjects\\autogenerateddata', '*.xlsx'):
    print('Found xlsx source:', filename)
    rows += readxlsx(filename)

for filename in find_files('C:\\Users\\HYPER\\PycharmProjects\\autogenerateddata', '*.xls'):
    print('Found xlsx source:', filename)
    rows += readxlsx(filename)

print('stolen ',len(rows), 'rows')
print(rows[0])

header = ['IDФизическогоЛица', '№ЗачетнойКнижки', 'КанцНомерПриказа', 'КанцДатаПриказа', 'ВидПриказа', 'ЗаголовокПриказа', 'ДатаНачала', 'ДатаОкончания', 'КодНаправленияПодготовки', 'ФормаОбучения', 'УчебныйГод', 'Курс', 'ОснованиеОбучения', 'УчебнаяГруппа', 'УчебнаяПодгруппа', 'Аналитика']
xlsxwrite(header, rows)
